"use client";

import React from "react";
import ThreeCardProjects from "./ui/ThreeCardProjects";
import ThreeCardGlobe from "./ui/ThreeCardGlobe";
import ThreeCardSatisfaction from "./ui/ThreeCardSatisfaction";
import ThreeCardFunnel from "./ui/ThreeCardFunnel";
import ThreeCardSpeed from "./ui/ThreeCardSpeed";
import ThreeCardRevenue from "./ui/ThreeCardRevenue";
import ScrollReveal from "./ui/ScrollReveal";

export default function WhyChooseUsSection() {
  const cards = [
    {
      stat: "200+",
      label: "Projects Delivered",
      visual: <ThreeCardProjects />,
      desc: "Behind every digital product we engineer is a human experience. We craft interfaces that blend aesthetic perfection with seamless utility.",
      glow: "bg-[radial-gradient(circle,rgba(212,249,56,0.08)_0%,transparent_70%)]",
    },
    {
      stat: "50+",
      label: "Global Digital Specialists",
      visual: <ThreeCardGlobe />,
      desc: "What started as an ambitious studio is now 50+ elite designers & digital engineers collaborating seamlessly across worldwide timezones.",
      glow: "bg-[radial-gradient(circle,rgba(56,189,248,0.08)_0%,transparent_70%)]",
    },
    {
      stat: "98%",
      label: "Client Retention & Trust",
      visual: <ThreeCardSatisfaction />,
      desc: "True partnership is measured by lasting impact. Our clients scale with us over the long term, backed by exceptional delivery and 5-star craft.",
      glow: "bg-[radial-gradient(circle,rgba(212,249,56,0.08)_0%,transparent_70%)]",
    },
    {
      stat: "15+",
      label: "Industries Served",
      visual: <ThreeCardFunnel />,
      desc: "Fintech, SaaS, AI, Web3, and Enterprise — we adapt seamlessly to your domain with deep industry acumen and tailored product strategy.",
      glow: "bg-[radial-gradient(circle,rgba(212,249,56,0.08)_0%,transparent_70%)]",
    },
    {
      stat: "48hr",
      label: "Average Kickoff Time",
      visual: <ThreeCardSpeed />,
      desc: "No prolonged onboarding or friction. We move at venture speed with agile sprints without ever cutting corners on engineering quality.",
      glow: "bg-[radial-gradient(circle,rgba(56,189,248,0.08)_0%,transparent_70%)]",
    },
    {
      stat: "$2B+",
      label: "Revenue Influenced",
      visual: <ThreeCardRevenue />,
      desc: "Capital raised and enterprise valuation generated by our partners over the past decade. Exceptional design compounds returns.",
      glow: "bg-[radial-gradient(circle,rgba(212,249,56,0.08)_0%,transparent_70%)]",
    },
  ];

  return (
    <section className="relative w-full bg-black text-white pt-14 sm:pt-18 pb-8 sm:pb-12 px-6 sm:px-12 lg:px-16 overflow-hidden">
      <div className="max-w-7xl mx-auto space-y-10 sm:space-y-12">
        {/* Section Heading */}
        <ScrollReveal distance={28} blur={14} duration={850}>
          <div className="text-center flex flex-col items-center justify-center space-y-4">
            <h2 className="text-2xl sm:text-4xl md:text-5xl lg:text-6xl font-black tracking-tight text-white leading-[1.18] font-['Questrial',sans-serif] max-w-4xl break-words px-2">
              Why brands choose Promethean Labs for
              <br />
              Design &amp; Digital experience?
            </h2>
          </div>
        </ScrollReveal>

        {/* 6 Interactive 3D WebGL Cards (2 Rows x 3 Columns) with ScrollReveal per Card */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 sm:gap-8">
          {cards.map((card, idx) => (
            <ScrollReveal
              key={idx}
              distance={36}
              blur={14}
              delay={(idx % 3) * 110}
              duration={900}
            >
              <div className="group relative rounded-[32px] bg-[#0c0d12] border border-neutral-800/80 p-7 sm:p-8 flex flex-col justify-between min-h-[470px] shadow-2xl transition-all duration-500 hover:border-neutral-600 hover:shadow-[0_20px_50px_rgba(212,249,56,0.06)] overflow-hidden">
                <div className="space-y-1 z-10">
                  <h3 className="text-4xl sm:text-5xl font-black text-white font-['Questrial',sans-serif] tracking-tight">
                    {card.stat}
                  </h3>
                  <p className="text-sm sm:text-base text-neutral-200 font-['Agrandir',sans-serif]">
                    {card.label}
                  </p>
                </div>
                <div className="my-2 flex items-center justify-center relative z-10">
                  {card.visual}
                </div>
                <div className="z-10 pt-2 border-t border-white/5">
                  <p className="text-xs sm:text-sm text-neutral-300 font-['Agrandir',sans-serif] leading-relaxed">
                    {card.desc}
                  </p>
                </div>
                <div className={`absolute top-0 right-0 w-48 h-48 ${card.glow} pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-700`} />
              </div>
            </ScrollReveal>
          ))}
        </div>
      </div>
    </section>
  );
}

